//Authentication
export const AUTHENTICATION_LOGIN = 'AUTHENTICATION_LOGIN';
export const AUTHENTICATION_SIGNUP = 'AUTHENTICATION_SIGNUP';
export const AUTHENTICATION_LOGOUT = 'AUTHENTICATIONLOGOUT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';